version: '3.8'

services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: 'develop-stage'
    container_name: erp.server
    volumes:
      - './server/:/var/www/html'
      - /var/www/html/node_modules
    command: bash -c "npm start dev"
    ports:
      - 3010:3000
      - 9229:9229
    restart: unless-stopped
    depends_on:
      - erp.mysql
    networks:
      - erp.network
    
  client:
    build:
      context: ./client/erp
      target: 'develop-stage'
      dockerfile: Dockerfile
    container_name: erp.client
    ports:
      - 8000:5173
    restart: unless-stopped
    volumes:
      - './client/erp:/app'
      - /app/node_modules
    tty: true
    networks:
      - erp.network

  erp.mysql:
    image: mysql:8.0
    container_name: erp.mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/data/db:/var/lib/mysql
    restart: always
    networks:
      - erp.network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3310:3306"

volumes:
  erp.mysql:

networks:
  erp.network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.5.0/25
